### ISSUE TITLE
Issue rendering headers in malformatted description file

### ISSUE THREAD

**Issue by tlambert03** [chanzuckerberg/napari-hub#438]
A plugin developer @loicsauteur came to the plugin meeting and mentioned a rendering issue (missing headers) on the hub page for his plugin:

https://www.napari-hub.org/plugins/napari-annotator

I wonder if it might have to do with the header level in [his description](https://github.com/loicsauteur/napari-annotator/blob/main/.napari/DESCRIPTION.md)?  (looks like there are multiple h1 headers)

not sure if it's possible to catch that and handle it gracefully?

**Comment by loicsauteur** [comment]
Hi
Just a short addition:
I actually used the DESCRIPTION template that came with cookiecutter, and kept the headings, which are all h1 headers.

**Comment by neuromusic** [comment]
oof, I'm sorry for the trouble here @loicsauteur 

> I wonder if it might have to do with the header level in [his description](https://github.com/loicsauteur/napari-annotator/blob/main/.napari/DESCRIPTION.md)?

I suspect you're right @tlambert03 ... iirc, we intentionally drop the first H1 header, since this typically restates the plugin name when we pull from the README content... but we're perhaps being too aggressive with the logic here.

> I actually used the DESCRIPTION template that came with cookiecutter, and kept the headings, which are all h1 headers.

this might be an oversight in the template

@loicsauteur if you can setup our preview page Github app [with the instructions here](https://github.com/chanzuckerberg/napari-hub/blob/main/docs/setting-up-preview.md), you can then get a live rendering of the hub listing on your pull requests... this will let you tweak the DESCRIPTION.md file and see how it changes the listing.

if you can try to drop the headings to H2 and confirm this with the preview page, then we can get the cookie-cutter template updated and fix the H1 bug

**Comment by liaprins-czi** [comment]
> given the more typical standards in the community for READMEs are to use H1 for the title and H2 for sections

It's also for accessibility to normally reserve the H1 for the page "title" (and concomitantly it is better for SEO if a page has just one `H1`). So if any of the cookie cutters we have use H1's throughout, we should consider updating them to just use it for the primary page heading / title, and then H2s instead wherever else an H1 was.

**Comment by neuromusic** [comment]
> It's also for accessibility

ohhhh interesting! thanks for that insight @liaprins-czi :D

**Comment by loicsauteur** [comment]
Hi @neuromusic 

> @loicsauteur if you can setup our preview page Github app [with the instructions here](https://github.com/chanzuckerberg/napari-hub/blob/main/docs/setting-up-preview.md), you can then get a live rendering of the hub listing on your pull requests... this will let you tweak the DESCRIPTION.md file and see how it changes the listing.
> 
> if you can try to drop the headings to H2 and confirm this with the preview page, then we can get the cookie-cutter template updated and fix the H1 bug

Thanks! I was not aware of this tool! 
**Changing to H2 made the preview nice!**

Yet, when I tried to create the preview, I ran into another problem.
the action threw an error (below), it expected a setup.py file in the repository. A file which was not present in the cookiecutter template...
Since, I am rather a newbie to all this, I just created a setup.py, with the same content as I found on another [napari plugin](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes). This allowed the action to finish and create the preview page. Yet, I am not sure if this will be an issue with my plugin (i.e. could I have just left an empty setup.py file)?


```
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
[584](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:584)
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.12/x64/bin/python -m pip install --upgrade pip' command.
[585](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:585)
Traceback (most recent call last):
[586](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:586)
  File "/home/runner/work/napari-annotator/napari-annotator/napari-hub/backend/preview/preview.py", line 132, in build_dist
[587](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:587)
    subprocess.run(
[588](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:588)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/subprocess.py", line 516, in run
[589](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:589)
    raise CalledProcessError(retcode, process.args,
[590](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:590)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.8.12/x64/bin/python', 'setup.py', 'bdist_wheel', '--dist-dir', '/home/runner/work/napari-annotator/napari-annotator']' returned non-zero exit status 2.
[591](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:591)

[592](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:592)
During handling of the above exception, another exception occurred:
[593](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:593)

[594](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:594)
Traceback (most recent call last):
[595](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:595)
  File "napari-hub/backend/get_preview.py", line 17, in <module>
[596](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:596)
    get_plugin_preview(repo_pth, dest_pth, args.local, args.branch)
[597](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:597)
  File "/home/runner/work/napari-annotator/napari-annotator/napari-hub/backend/preview/preview.py", line 39, in get_plugin_preview
[598](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:598)
    wheel_pth = build_dist(repo_pth, dest_dir)
[599](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:599)
  File "/home/runner/work/napari-annotator/napari-annotator/napari-hub/backend/preview/preview.py", line 139, in build_dist
[600](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:600)
    raise RuntimeError(
[601](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:601)
RuntimeError: Could not build distribution for package at /home/runner/work/napari-annotator/napari-annotator.
[602](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:602)
b"/opt/hostedtoolcache/Python/3.8.12/x64/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory\n"
[603](https://github.com/loicsauteur/napari-annotator/runs/5498503554?check_suite_focus=true#step:3:603)
Error: Process completed with exit code 1.
```

**Comment by tlambert03** [comment]
> I just created a setup.py, with the same content as I found on another [napari plugin](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes).

In general, it's not a safe assumption that other plugins are following best practice :)  so definitely let us know if instructions you find in the napari repo or the cookiecutter aren't working for you.

In this case, I think this is a bug in the napari preview bot.  Specifically, the `preview.py` is [directly invoking `setup.py` right here.](https://github.com/chanzuckerberg/napari-hub/blob/f5f1f884e991884aa5ed936d93c71bf4cbd3ed97/backend/preview/preview.py#L133).  

@neuromusic: Direct invocation of setup.py is deprecated (see explanation from setuptools dev [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)).  The cookiecutter doesn't even have a setup.py anymore.  I mentioned this to ziyang in zulip a while back, but it looks like the preview bot is still directly calling setup.py.  You should [use the build package](https://pypa-build.readthedocs.io/en/stable/index.html) (`python -m build`)  to build

**Comment by tlambert03** [comment]
@loicsauteur 

yes, you could add an empty setup.py for now (just including `from setuptools import setup; setup()`) ... but you shouldn't have to.

**Comment by loicsauteur** [comment]
@tlambert03 
Thanks for the feedback. 
I thought it could be bug coming from the preview bot... Hence, me adding this `setup.py` file, which is (luckily) just `from setuptools import setup; setup()` and got the preview working.

**Comment by neuromusic** [comment]
OK, I've created issues related to the two bugs this surfaced & opened a PR to improve the cookiecutter.

Thanks for your help @tlambert03 and glad we could get you unstuck @loicsauteur :D
