### ISSUE TITLE
Prewiew action fail wit to many redirect

### ISSUE THREAD

**Issue by Czaki** [chanzuckerberg/napari-hub#540]
#### Description

run `chanzuckerberg/napari-hub-preview-action@v0.1.5` end with following error:

```
Traceback (most recent call last):
  File "napari-hub/backend/get_preview.py", line 17, in <module>
    get_plugin_preview(repo_pth, dest_pth, args.local, args.branch)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/preview/preview.py", line 74, in get_plugin_preview
    get_pypi_date_meta(meta)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/preview/preview.py", line 243, in get_pypi_date_meta
    pypi_info = get_plugin_pypi_metadata(name, version=None)
  File "/home/runner/work/PartSeg/PartSeg/napari-hub/backend/utils/pypi.py", line 57, in get_plugin_pypi_metadata
    response = requests.get(url)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

#### Steps/Code to Reproduce

https://github.com/4DNucleome/PartSeg/runs/6829608548?check_suite_focus=true#step:3:630

#### Expected Results

working GitHub action

**Comment by neuromusic** [comment]
thanks @Czaki 

any ideas @DragaDoncila ?

**Comment by DragaDoncila** [comment]
@Czaki I've struggled to reproduce this locally, even after thousands of calls to preview page build. Can you advise whether you're seeing this frequently on your PRs or if it's sporadic? It may be an issue with using `requests` in a GitHub Action but if it's very sporadic we may struggle to reproduce it.

**Comment by Czaki** [comment]
I see 3 in last runs (and some solved by restart) https://github.com/4DNucleome/PartSeg/actions/workflows/plugin_preview.yml

Maybe some catch of error and retry after a few seconds?

**Comment by DragaDoncila** [comment]
@Czaki thanks for that added context. Yeah if you're seeing that frequently I think we should catch and retry, if we can't figure out how to stop it from happening.
