### ISSUE TITLE
Wiki docs must upgrade napari-hub preview action to v0.1.6

### ISSUE THREAD

**Issue by GenevieveBuckley** [chanzuckerberg/napari-hub#924]
#### Description

The [wiki page](https://github.com/chanzuckerberg/napari-hub/wiki/Setting-up-the-napari-hub-Plugin-Preview-Page-for-your-PRs) describing setting up the napari-hub preview plugin refers to an outdated version of the action, which causes an error when the CI runs. 

Here is the wiki page that needs editing:
https://github.com/chanzuckerberg/napari-hub/wiki/Setting-up-the-napari-hub-Plugin-Preview-Page-for-your-PRs

In section **"2. Set up the GitHub workflow"**, this line needs to be changed to use version 0.1.6 (instead of 0.1.5):
```yaml
uses: chanzuckerberg/napari-hub-preview-action@v0.1.6
````

#### Why this change is needed

Draga recently made some changes to the preview action, requiring `npe2` as a requirement:
- https://github.com/chanzuckerberg/napari-hub-preview-action/pull/5
- https://github.com/chanzuckerberg/napari-hub/pull/711

If users don't upgrade the napari-hub preview action to version 0.1.6, then when the action runs there is this error:
```
ModuleNotFoundError: No module named 'npe2'
````
#### Steps/Code to Reproduce
You can reproduce this error by running the napari-hub preview action version 0.1.5 or lower on any repo you already have set up.

#### Expected Results
I expected the napari-hub preview action to run, and show me a preview of the page.

#### Actual Results
Instead, if users don't upgrade the napari-hub preview action to version 0.1.6, then when the action runs there is this error:
```
ModuleNotFoundError: No module named 'npe2'
````

[Here is the github action CI output](https://github.com/GenevieveBuckley/napari-meshio/actions/runs/4341190181) for a repository of mine [napari-meshio](https://github.com/GenevieveBuckley/napari-meshio):

<details>
<summary>Github action CI error:</summary>

```
Run chanzuckerberg/napari-hub-preview-action@v0.1.5
Run actions/checkout@v2
Syncing repository: chanzuckerberg/napari-hub
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/d69cce02-99d1-4060-8bfd-695e270b39c8' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/napari-meshio/napari-meshio/napari-hub
Initializing the repository
Disabling automatic garbage collection
Setting up auth
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 21.8 MB/s eta 0:00:00
Collecting docopt>=0.6.2
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting ruamel.yaml.clib>=0.2.6
  Downloading ruamel.yaml.clib-0.2.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (555 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.3/555.3 kB 92.7 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.4-py3-none-any.whl (37 kB)
Collecting uritemplate>=3.0.0
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Installing collected packages: pytz, docopt, asn1crypto, zipp, wrapt, wheel, urllib3, uritemplate, typing-extensions, tomli, tenacity, soupsieve, smmap, six, setuptools, ruamel.yaml.clib, pyyaml, pyrsistent, pyjwt, pycryptodomex, pycparser, protobuf, pkginfo, packaging, oscrypto, numpy, MarkupSafe, jmespath, itsdangerous, idna, filelock, decorator, click, charset-normalizer, certifi, attrs, apig-wsgi, Werkzeug, ruamel.yaml, requests, python-dateutil, pep517, jsonschema, Jinja2, importlib-metadata, gunicorn, gitdb, ddtrace, cffi, beautifulsoup4, pykwalify, pandas, Markdown, GitPython, Flask, datadog, cryptography, build, bs4, botocore, s3transfer, pyOpenSSL, datadog-lambda, cffconvert, snowflake-connector-python, github3.py, boto3, Flask-GitHubApp
  DEPRECATION: docopt is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for docopt: started
  Running setup.py install for docopt: finished with status 'done'
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
  DEPRECATION: bs4 is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for bs4: started
  Running setup.py install for bs4: finished with status 'done'
  DEPRECATION: Flask-GitHubApp is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Flask-GitHubApp: started
  Running setup.py install for Flask-GitHubApp: finished with status 'done'
Successfully installed Flask-2.2.1 Flask-GitHubApp-0.3.0 GitPython-3.1.30 Jinja2-3.1.2 Markdown-3.4.1 MarkupSafe-2.1.2 Werkzeug-2.2.3 apig-wsgi-2.14.0 asn1crypto-1.5.1 attrs-22.2.0 beautifulsoup4-4.11.2 boto3-1.24.46 botocore-1.27.96 bs4-0.0.1 build-0.8.0 certifi-2022.12.7 cffconvert-2.0.0 cffi-1.15.1 charset-normalizer-2.0.12 click-8.1.3 cryptography-36.0.2 datadog-0.41.0 datadog-lambda-3.60.0 ddtrace-0.61.5 decorator-5.1.1 docopt-0.6.2 filelock-3.9.0 gitdb-4.0.10 github3.py-3.2.0 gunicorn-20.1.0 idna-3.4 importlib-metadata-6.0.0 itsdangerous-2.1.2 jmespath-1.0.1 jsonschema-3.2.0 numpy-1.24.2 oscrypto-1.3.0 packaging-23.0 pandas-1.4.4 pep517-0.13.0 pkginfo-1.8.3 protobuf-3.20.3 pyOpenSSL-22.0.0 pycparser-2.21 pycryptodomex-3.17 pyjwt-2.6.0 pykwalify-1.8.0 pyrsistent-0.19.3 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 requests-2.28.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7 s3transfer-0.6.0 setuptools-65.5.1 six-1.16.0 smmap-5.0.0 snowflake-connector-python-2.8.0 soupsieve-2.4 tenacity-8.2.2 tomli-2.0.1 typing-extensions-4.5.0 uritemplate-4.1.1 urllib3-1.26.14 wheel-0.38.1 wrapt-1.15.0 zipp-3.15.0
Traceback (most recent call last):
  File "napari-hub/backend/get_preview.py", line 17, in <module>
    get_plugin_preview(repo_pth, dest_pth, args.local, args.branch)
  File "/home/runner/work/napari-meshio/napari-meshio/napari-hub/backend/preview/preview.py", line 41, in get_plugin_preview
    meta = parse_meta(wheel_pth)
  File "/home/runner/work/napari-meshio/napari-meshio/napari-hub/backend/preview/preview.py", line 179, in parse_meta
    from npe2 import get_manifest_from_wheel
ModuleNotFoundError: No module named 'npe2'
Error: Process completed with exit code 1.
```

</details>

**Comment by GenevieveBuckley** [comment]
Although honestly maybe there's a better place for a "single source of truth" yaml script? 

I feel it is very unlikely people will remember to update this wiki location when future breaking changes are made. It's just too separate from the repositories and code people are actually editing.

**Comment by richaagarwal** [comment]
Thanks so much for the report and detailed notes, @GenevieveBuckley.  I've made the change to the wiki, and I agree the current documentation structure is less than ideal. I'll give it some thought; we can also modify the language to reference the "latest version" rather than hardcoding it.

**Comment by GenevieveBuckley** [comment]
> we can also modify the language to reference the "latest version" rather than hardcoding it

Yes, this might work. Even better if you can add a link next to "the latest version" that takes you to the releases page so people can check what the latest version number actually is.
